# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: One Piece
email: funnymaster@gmail.com
description: >
  We are NOT asking him where the treasure is hidden!!!
  We're not even asking him whether there IS any treasure or not!!
  I'm not sure, but...
  ...everybody set out to sea, risking their lives to search for it!!!
  If you ask this old man anything about it here and now...
  Then I'll quit being a pirate!
  I don't want to go on a boring adventure like that!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  o-p

# Build settings
markdown: kramdown
theme: minima
