# {{ site.variableName }}

title: One Piece
email: funnymaster@gmail.com
description: >
  We are NOT asking him where the treasure is hidden!!!
  We're not even asking him whether there IS any treasure or not!!
  I'm not sure, but...
  ...everybody set out to sea, risking their lives to search for it!!!
  If you ask this old man anything about it here and now...
  Then I'll quit being a pirate!
  I don't want to go on a boring adventure like that!

baseurl: "/robin"
url: "https://o-p.github.io"
twitter_username: poOovoOoq
github_username:  o-p

# Build settings
markdown: kramdown
theme: minima

# Disqus
disqus:
  shortname: one-piece
  
